FROM node:22-alpine

WORKDIR /app
RUN chown node:node /app

COPY --chown=node:node package*.json ./
USER node
RUN npm install

COPY --chown=node:node . .

EXPOSE 3001

CMD ["npm", "run", "dev"]